require("pankajgarkoti.plugins-setup")
require("pankajgarkoti.core.options")
require("pankajgarkoti.core.keymaps")
require("pankajgarkoti.plugins.comment")
require("pankajgarkoti.plugins.nvim-tree")
require("pankajgarkoti.plugins.lualine")
require("pankajgarkoti.plugins.telescope")
require("pankajgarkoti.plugins.CoC.coc")
require("pankajgarkoti.plugins.autopairs")
require("pankajgarkoti.plugins.treesitter")
require("pankajgarkoti.plugins.gitsigns")
-- require("pankajgarkoti.core.colorscheme_gruvbox")
require("pankajgarkoti.core.colorscheme_catppuccin")
-- require("pankajgarkoti.plugins.copilot")
-- require("pankajgarkoti.core.colorscheme_material")
-- require("pankajgarkoti.core.colorscheme_catppuccin")
-- require("pankajgarkoti.plugins.nvim-cmp")
require("pankajgarkoti.plugins.lsp.mason")
-- require("pankajgarkoti.plugins.lsp.lspsaga")
-- require("pankajgarkoti.plugins.lsp.lspconfig")
require("pankajgarkoti.plugins.lsp.null-ls")
