require("pankajgarkoti.plugins-setup")
require("pankajgarkoti.core.options")
require("pankajgarkoti.core.keymaps")
require("pankajgarkoti.core.colorscheme")
require("pankajgarkoti.plugins.comment")
require("pankajgarkoti.plugins.nvim-tree")
require("pankajgarkoti.plugins.lualine")
require("pankajgarkoti.plugins.telescope")
require("pankajgarkoti.plugins.nvim-cmp")
-- require("pankajgarkoti.plugins.CoC.coc")
-- require("pankajgarkoti.plugins.lsp.mason")
-- require("pankajgarkoti.plugins.lsp.lspsaga")
-- require("pankajgarkoti.plugins.lsp.lspconfig")
-- require("pankajgarkoti.plugins.lsp.null-ls")
require("pankajgarkoti.plugins.autopairs")
require("pankajgarkoti.plugins.treesitter")
require("pankajgarkoti.plugins.gitsigns")
