import = [
    "~/.config/alacritty/themes/themes/challenger_deep.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.bold]
family = "IosevkaTerm Nerd Font Mono"
style = "Heavy"

[font.bold_italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Heavy Italic"

[font.italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Medium"

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 1

[window.padding]
x = 0
y = 0

[window.dimensions]
lines = 50
columns = 180

[shell]
program = "/bin/zsh"
args = [  "-l", "-c", "cd ~/Desktop/code/; tmux attach -t code || tmux new -t code" ]
