import = [
    "~/.config/alacritty/themes/themes/carbonfox.toml"
]
live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 18.0

[font.bold]
family = "IosevkaTerm Nerd Font Mono"
style = "Heavy"

[font.bold_italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Heavy Italic"

[font.italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Medium"

[cursor.style]
shape = "Underline"
blinking = "Always"

[cursor.vi_mode_style]
shape = "Underline"
blinking = "Always"

[mouse]
hide_when_typing = true

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 0.7
blur = true
resize_increments = true

[window.padding]
x = 0
y = 0

[window.dimensions]
lines = 68
columns = 260


[shell]
program = "/bin/zsh"
args = [  "-l", "-c", "cd ~/Desktop/code/; tmux attach -t code || tmux new -t code" ]
