live_config_reload = true

[font]
size = 16.0

[font.bold]
family = "IosevkaTerm Nerd Font Mono"
style = "Heavy"

[font.bold_italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Heavy Italic"

[font.italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Medium"

[cursor.style]
shape = "Underline"
blinking = "Never"

[cursor]
thickness = 0.5

[mouse]
hide_when_typing = true

[window]
decorations = "Buttonless"
dynamic_padding = true
opacity = 1
blur = false
resize_increments = false

[window.dimensions]
lines = 68
columns = 260

# Colors (Dracula+)

[colors.primary]
background = '#282a36'
foreground = '#f8f8f2'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#ff5555'
green   = '#50fa7b'
yellow  = '#f1fa8c'
blue    = '#bd93f9'
magenta = '#ff79c6'
cyan    = '#8be9fd'
white   = '#bbbbbb'

# Bright colors
[colors.bright]
black   = '#555555'
red     = '#ff5555'
green   = '#50fa7b'
yellow  = '#f1fa8c'
blue    = '#caa9fa'
magenta = '#ff79c6'
cyan    = '#8be9fd'
white   = '#ffffff'

# [shell]
# program = "/bin/zsh"
# args = [  "-l", "-c", "cd ~/Desktop/code/; tmux attach -t code || tmux new -t code" ]
