live_config_reload = true

[font]
size = 16.0

[font.bold]
family = "IosevkaTerm Nerd Font Mono"
style = "Heavy"

[font.bold_italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Heavy Italic"

[font.italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
# style = "Regular"
style = "Heavy"

[cursor.style]
shape = "Underline"
blinking = "Never"

[cursor]
thickness = 0.5

[mouse]
hide_when_typing = true

[window]
decorations = "Buttonless"
dynamic_padding = true
resize_increments = false
opacity = 0.7
blur = true


[window.dimensions]
lines = 68
columns = 260


# (Github Dark Tritanopia) Colors for Alacritty
# Default colors
[colors.primary]
background = '#0d1117'
# background = '#00131E'
# background = "#000000"
foreground = '#c9d1d9'

# Cursor colors
[colors.cursor]
text = '#0d1117'
cursor = '#c9d1d9'

# Normal colors
[colors.normal]
black = '#484f58'
red = '#ff7b72'
green = '#58a6ff'
yellow = '#d29922'
blue = '#58a6ff'
magenta = '#bc8cff'
cyan = '#39c5cf'
# white = '#b1bac4'
white = '#ffffff'

# Bright colors
[colors.bright]
black = '#6e7681'
red = '#ffa198'
green = '#79c0ff'
yellow = '#e3b341'
blue = '#79c0ff'
magenta = '#bc8cff'
cyan = '#39c5cf'
# white = '#b1bac4'
white = '#ffffff'
