[general]
import = [
    "~/.config/alacritty/themes/themes/tokyo_night_enhanced.toml",
]
live_config_reload = true

[font]
size = 16

[font.bold]
family = "IosevkaTerm Nerd Font Mono"
style = "Heavy"

[font.bold_italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Heavy Italic"

[font.italic]
family = "IosevkaTerm Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Medium"

[mouse]
hide_when_typing = true

[window]
decorations = "Buttonless"
dynamic_padding = true
resize_increments = false
# opacity = 0.8  # Add this line (0.95 = 95% opaque)
# blur = true

[window.dimensions]
lines = 72
columns = 300
